on:
  push:
    branches:
    - main

jobs:
  build-vite:
    name: "Build Vite application"
    runs-on: ubuntu-22.04
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '20.x'
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.0.0

    - name: Build application
      run: |
        pnpm i
        pnpm run build

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist # The folder the action should deploy.
